# Default: undefined
#user: 'node'
#group: 'nogroup'

#=====================================================================

# Configuration of the embedded HTTP server.
http:
  listen:
    # Basic HTTP.
    -
      host: '0.0.0.0'
      port: 8000
  mounts:
    '/': '/root/xen-orchestra/packages/xo-web/dist/'

#=====================================================================

# Connection to the Redis server.
redis:
    # Syntax: redis://[db[:password]@]hostname[:port]
    uri: "redis://redis:6379"

datadir: '/storage/data'

