#!/bin/bash

echo "[***] Build hook - retrieve XOA versions"

# get version number from package.json in the remote repo
XOSERVER=$(curl -s https://raw.githubusercontent.com/vatesfr/xen-orchestra/master/packages/xo-server/package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])")
XOWEB=$(curl -s https://raw.githubusercontent.com/vatesfr/xen-orchestra/master/packages/xo-web/package.json | python -c "import sys, json; print(json.load(sys.stdin)['version'])")
VERSION=$(echo ${XOSERVER} | sed -rn 's/([[:digit:]]+\.[[:digit:]]+)\..*/\1/p')

echo "[***] Build hook - build XOA docker image version ${VERSION}: xoserver-${XOSERVER} xoweb-${XOWEB}"

MY_IMAGE_NAME=${IMAGE_NAME:-"ezka77/xen-orchestra-ce:latest"}

docker build \
    --build-arg VERSION=${VERSION}   \
    --build-arg XOSERVER=${XOSERVER} \
    --build-arg XOWEB=${XOWEB}       \
    -t ${MY_IMAGE_NAME} .
