#!/bin/bash

# Add a tag with the latest build

# Find a way to inspect the laster build image ?
#VERSION=$(docker inspect --format='{{ index .Config.Labels "version" }}' ${IMAGE_NAME})

echo "[***] Post-Build hook - retrieve XOA version"
VERSION=$(curl -s https://raw.githubusercontent.com/vatesfr/xen-orchestra/master/packages/xo-server/package.json | python -c "import sys, json; print(".".join(json.load(sys.stdin)['version'].split('.')[0:2]))")

# if we fail to retrieve a correct version number, exit!
if [ -z ${VERSION} ]; then
  echo "[***] Post-Build hook - Version number is empty!"
  exit 0
fi

# if Version not empty push it as a tag

echo "[***] Post-Build hook - Adding tag ${VERSION}"

docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${VERSION}
docker push ${DOCKER_REPO}:${VERSION}
